 GET http://localhost:5050/users
### 
GET http://localhost:5050/users/64a0b48d78856490d35902e9
###
POST http://localhost:5050/users
Content-Type: application/json


{
    "userName": "lindfund",
    "password": "Test"
}
###
DELETE http://localhost:5050/users/64a0b48d78856490d35902e9

###
PATCH  http://localhost:5050/users/64a0b48d78856490d35902e9
Content-Type: application/json


{
    "password": "ItWorks!"
}

//Render
### GET https://cse341-gardenseeds.onrender.com/seeds
### GET https://cse341-gardenseeds.onrender.com/seeds/649b3c1d1add738f327ab0f5

//swagger
### GET https://localhost:5050/apiDocs/


