 //LOCALHOST TESTING
 GET http://localhost:5050/users
### 
GET http://localhost:5050/users/64a0b48d78856490d35902e9
###
POST http://localhost:5050/users
Content-Type: application/json

{
    "userName": "HoraceSlugHorn",
    "password": "1234"
}
###
DELETE http://localhost:5050/users/64a0e76728e3d149eb7320a1

###
PATCH  http://localhost:5050/users/64a0b48d78856490d35902e9
Content-Type: application/json


{
    "password": "ItWorks"
}

//Render
### 
GET https://cse341-gardenseeds.onrender.com/users
### 
GET https://cse341-gardenseeds.onrender.com/users/64a0b6fff01d39095535324f

//swagger
### 
GET https://localhost:5050/apiDocs/


